version: 2

sources: 
  - name: northwind
    database: sdw
    schema: raw
    tables:
      - name: categories
      - name: customers
      - name: employees
      - name: order_details
      - name: orders
      - name: products
      - name: shippers
      - name: suppliers
      - name: dim_product
      - name: dim_employee
      - name: dim_customer
      - name: dim_date
      - name: dim_fact_sales
      - name: obt
      - name: customer_spend_accumulating_fact

      
      